---
- hosts: prometheus 
  remote_user: qwerbo
  become: yes
  become_method: sudo


  roles: 
    - ansible-prometheus 
  vars:
    prometheus_targets:
      node:
      - targets:
        - 10.0.1.3:9100
        - 10.0.2.3:9100
        - 10.0.1.3:4040
        - 10.0.2.3:4040
        labels:
          env: demosite
        #- demo.cloudalchemy.org:9100
