---

- hosts: grafana
  remote_user: qwerbo
  become: yes
  become_method: sudo
  
  
  roles:
    - role: grafana
      vars:
        grafana_version: latest
        grafana_security:
          admin_user: admin
          admin_password: admin 
        grafana_datasources:
          - name: prometheus
            type: prometheus
            access: proxy
            url: "http://{{ groups['prometheus'][0] }}:9090"
            basicAuth: false
        #grafana_dashboards:
        #- dashboard_id: 11074 
          #revision_id: 9
          #datasource: prometheus
        #- dashboard_id: 15947 
          #revision_id: 1
          #datasource: prometheus