{
 "title": "MyDashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UTILIZATION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100-avg(irate(node_cpu_seconds_total{job='node',mode=\"idle\"}[5m]))by (instance)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SATURATION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_load1/count without (cpu) (count without(mode)(node_cpu_seconds_total))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network (Arrival_traffic)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node\", device=\"eth0\"}[5m])*8/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network (departude_traffic)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node\", device=\"eth0\"}[5m])*8/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HDD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "HDD (WebServer-2)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/vda2\", instance=\"10.0.2.3:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/vda2\", instance=\"10.0.2.3:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/vda2\", instance=\"10.0.2.3:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HDD WebServer-1",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/vda2\", instance=\"10.0.1.3:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/vda2\", instance=\"10.0.1.3:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_free_bytes{instance=\"10.0.1.3:9100\", device=\"/dev/vda2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "RAM (MemFREE)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP_WEB1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Http_count_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nginx_http_response_count_total{instance=\"10.0.1.3:4040\", status=\"200\"}",
     "legendFormat": "Get=200"
    },
    {
     "expr": "nginx_http_response_count_total{instance=\"10.0.1.3:4040\", status=\"404\"}",
     "legendFormat": "Get=400"
    }
   ]
  },
  {
   "title": "Http_size_bytes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_http_response_size_bytes{instance=\"10.0.1.3:4040\", status=\"200\"}",
     "legendFormat": "GET = 200"
    },
    {
     "expr": "nginx_http_response_size_bytes{instance=\"10.0.1.3:4040\", status=\"404\"}",
     "legendFormat": "GET = 404"
    }
   ]
  }
 ]
}